Repository KNUChat/KNUChat, pull requests merged in 2023-12, with the labels that each got.

#37 Feat/issue #34
  src/components/Chat/ChatBoxLeft.tsx
  src/components/Chat/ChatBoxRight.tsx
  src/components/Chat/ChatListTitle.tsx
  src/components/Chat/ChatPrintBox.tsx
  src/components/Chat/ChatTextBox.tsx
  src/components/Chat/Chatlist.tsx
  src/components/Chat/Chatroom.tsx
  src/components/Chat/ChatroomBox.tsx
  src/page/Chat.tsx
  src/store/store.tsx
  src/template/CommonTemplate.tsx
  src/websocket/ConnectHandler.tsx
Labels: ✨ Feature, 📬 API

#43 axios, api, hook(record, user) 구현 완료
  db.json
  package.json
  src/api/auth.ts
  src/api/axios.ts
  src/api/record.ts
  src/api/user.ts
  src/components/MyPage/ProfileTab.tsx
  src/components/MyPage/RecordTab.tsx
  src/hook/record/useAddRecord.ts
  src/hook/record/useDeleteRecord.ts
  src/hook/record/useGetRecord.ts
  src/hook/record/usePatchRecord.ts
  src/hook/record/useSearchRecord.ts
  src/hook/user/useDeleteUserProfile.ts
  src/hook/user/useGetUserProfile.ts
  src/hook/user/useInitUserProfile.ts
  src/hook/user/useSearchUserProfile.ts
  src/hook/user/useSignIn.ts
  src/hook/user/useSignUp.ts
  src/hook/user/useUpdateUserProfile.ts
  src/main.tsx
  src/page/Test.tsx
  src/routes/router.tsx
  src/vite-env.d.ts
  vite.config.ts
  yarn.lock
Labels: ✨ Feature, 📃 Docs, 📬 API

#46 Chat 기능 보수
  db.json
  package.json
  src/api/auth.ts
  src/api/axios.ts
  src/api/record.ts
  src/api/user.ts
  src/components/Chat/ChatPrintBox.tsx
  src/components/Chat/ChatTextBox.tsx
  src/components/Chat/Chatlist.tsx
  src/components/Chat/Chatprofile.tsx
  src/components/Chat/Chatroom.tsx
  src/components/Chat/ChatroomBox.tsx
  src/components/Chat/MakeRoom.tsx
  src/components/Chat/Profile.tsx
  src/components/Chat/Title.tsx
  src/components/MyPage/ProfileTab.tsx
  src/components/MyPage/RecordTab.tsx
  src/hook/record/useAddRecord.ts
  src/hook/record/useDeleteRecord.ts
  src/hook/record/useGetRecord.ts
  src/hook/record/usePatchRecord.ts
  src/hook/record/useSearchRecord.ts
  src/hook/user/useDeleteUserProfile.ts
  src/hook/user/useGetUserProfile.ts
  src/hook/user/useInitUserProfile.ts
  src/hook/user/useSearchUserProfile.ts
  src/hook/user/useSignIn.ts
  src/hook/user/useSignUp.ts
  src/hook/user/useUpdateUserProfile.ts
  src/main.tsx
  src/page/Test.tsx
  src/routes/router.tsx
  src/store/store.tsx
  src/vite-env.d.ts
  src/websocket/ConnectHandler.tsx
  src/websocket/SubHandler.tsx
  vite.config.ts
  yarn.lock
Labels: 🐞 BugFix, ✨ Feature

#61 Feat/issue #59
  src/components/Chat/Chat.tsx
  src/components/Chat/ChatPrintBox.tsx
  src/components/Chat/ChatTextBox.tsx
  src/components/Chat/ChatroomBox.tsx
Labels: 🎨 Html&css, 🐞 BugFix, ✨ Feature, 📬 API

#63 이력 작성 페이지 관련 api 연결 및 pagination 추가
  src/api/axios.ts
  src/api/record.ts
  src/components/Common/DefaultInput.tsx
  src/components/Common/HashTagInput.tsx
  src/components/MyPage/ContentBox.tsx
  src/components/MyPage/ProfileTab.tsx
  src/components/MyPage/RecordTab.tsx
  src/components/Profile/ProfileContent.tsx
  src/components/Record/AddRecord.tsx
  src/components/Record/DateRangePicker.tsx
  src/components/Record/RecordContent.tsx
  src/hook/record/useAddRecord.ts
  src/hook/record/useSearchRecord.ts
Labels: 🎨 Html&css, 🐞 BugFix, ✨ Feature, 📬 API

#64 검색창 api 연결 및 router 작업 진행
  package.json
  src/components/Layout/Navbar.tsx
  src/components/MyPage/MainContent.tsx
  src/components/Search.tsx
  src/page/Search.tsx
  src/routes/router.tsx
  src/store/useSearchStore.tsx
  yarn.lock
Labels: 🎨 Html&css, ✨ Feature, 📬 API

#73 waiting chat room 기능 추가 구현
  src/components/Chat/ButtonBox.tsx
  src/components/Chat/ChatListNav.tsx
  src/components/Chat/Chatlist.tsx
  src/components/ChatManage/MangeProfile.tsx
  src/store/useChatStore.tsx
Labels: 🎨 Html&css, ✨ Feature

#76 Chat 날짜 출력 구현 완료
  src/components/Chat/ChatPrintBox.tsx
  src/components/Chat/Chatroom.tsx
  src/components/Chat/PrintDate.tsx
  src/store/useChatStore.tsx
Labels: 🎨 Html&css, ✨ Feature
